logging:
  #\u8BBE\u7F6E\u65E5\u5FD7\u7EC4
  group:
    #\u81EA\u5B9A\u4E49\u7EC4\u540D\uFF0C\u8BBE\u7F6E\u5F53\u524D\u7EC4\u4E2D\u6240\u5305\u542B\u7684\u5305
    ebank: com.yeyu.springboot2_day_12.controller
  level:
    root: warn
  #\u4E3A\u5BF9\u5E94\u7EC4\u8BBE\u7F6E\u65E5\u5FD7\u7EA7\u522B
  ebank: debug
  #\u4E3A\u5BF9\u5E94\u5305\u8BBE\u7F6E\u65E5\u5FD7\u7EA7\u522B
  com.yeyu.springbooy2_day_12.controller: debug
  pattern:
    #console: "%d - %m%n"
    console: "%d %clr(%p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"